  stripe:
   payment_retry_limit: 3,
   payment_retry_periods:
     [1,1,1]
  premium_plan_launch_offer_end: 31 July 2013
  plans:
    personal:
      price: 9
      description_brief: For small scale projects
      urls_per_job: 50
      credits_per_month: 5000
    agency:
      price: 19
      description_brief: Great for small organisations
      urls_per_job: 250
      credits_per_month: 20000
    business:
      price: 59
      description_brief: Best value for professionals
      urls_per_job: 2500
      credits_per_month: 100000
    enterprise:
      price: 299
      description_brief: Full corporate treatment
      urls_per_job: 10000
      credits_per_month: unlimited      