stripe_event:
  pattern: /stripe/event/
  defaults: { _controller: SimplyTestableWebClientBundle:Stripe\Event:index, _format: json }  
  
mailchimp_event:
  pattern: /mailchimp/event/
  defaults: { _controller: SimplyTestableWebClientBundle:MailChimp\Event:index, _format: json }     

sign_out_submit:
    pattern:  /signout/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signOutSubmit }   

view_user_signin_index:
    pattern:  /signin/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/SignIn:index }
    
sign_in_submit:
    pattern:  /signin/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signInSubmit }     
    
view_user_resetpassword_index_index:
    pattern:  /reset-password/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/ResetPassword/Index:index }
    
reset_password_submit:
    pattern:  /reset-password/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:User:resetPasswordSubmit }     

reset_password_choose_submit:
    pattern:  /reset-password/choose/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:User:resetPasswordChooseSubmit }       
    
view_user_resetpassword_choose_index:
    pattern:  /reset-password/{email}/{token}/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/ResetPassword/Choose:index }
    
view_user_signup_index_index:
    pattern:  /signup/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/SignUp/Index:index }
    
sign_up_submit:
    pattern:  /signup/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signUpSubmit }   
    
view_user_signup_confirm_index:
    pattern:  /signup/confirm/{email}/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/SignUp/Confirm:index }
    
sign_up_confirm_submit:
    pattern:  /signup/confirm/{email}/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signUpConfirmSubmit }     
    
sign_up_confirm_resend:
    pattern:  /signup/confirm/{email}/resend/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signUpConfirmResend }
    
user_account_details_update:
    pattern:  /account/details/update/
    defaults: { _controller: SimplyTestableWebClientBundle:UserAccountDetails:update }          
    
user_subscription_choices_update:
    pattern:  /account/news-subscriptions/update/
    defaults: { _controller: SimplyTestableWebClientBundle:UserNewsSubscriptions:update }    
    
user_account_details_confirm_email_change:
    pattern:  /account/details/update/confirm-email-change/
    defaults: { _controller: SimplyTestableWebClientBundle:UserAccountDetails:confirmEmailChange }          

view_user_account_index_index:
    pattern:  /account/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/Account/Index:index }
    
view_user_account_card_index:
    pattern:  /account/card/
    defaults: { _controller: SimplyTestableWebClientBundle:View/User/Account/Card:index }
    
user_account_card_associate:
    pattern:  /account/card/{stripe_card_token}/associate/
    defaults: { _controller: SimplyTestableWebClientBundle:UserAccountCard:associate }        
    
user_account_plan_subscribe:
    pattern:  /account/plan/subscribe/
    defaults: { _controller: SimplyTestableWebClientBundle:UserAccountPlan:subscribe }    

app:
    pattern:  /
    defaults: { _controller: SimplyTestableWebClientBundle:App:index }
    
app_current:    
    pattern:  /current/
    defaults: { _controller: SimplyTestableWebClientBundle:App:current, _format: json  }
    
app_current_content:    
    pattern:  /current-content/
    defaults: { _controller: SimplyTestableWebClientBundle:App:currentContent }    
    
app_finished_content:    
    pattern:  /finished-content/
    defaults: { _controller: SimplyTestableWebClientBundle:App:finishedContent }      

view_test_history_index_index:
    pattern:  /history/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/History/Index:index, page_number: 1 }
    
app_history:
    pattern:  /history/{page_number}/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/History/Index:index }
    requirements:
        page_number: "\d+"    
    
app_history_websites:
    pattern:  /history/websites/
    defaults: { _controller: SimplyTestableWebClientBundle:TestHistory:websites, _format: json }     
    
app_test_finished_summary:
    pattern:  /{website}/{test_id}/finished-summary/
    defaults: { _controller: SimplyTestableWebClientBundle:TestResults:finishedSummary }     
    requirements:
        website: ".+"
        test_id: "\d+"

view_test_results_partial_finishedsummary_index:
    pattern:  /{website}/{test_id}/finished-summary-bs3/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/Partial/FinishedSummary/Index:index }
    requirements:
        website: ".+"
        test_id: "\d+"

view_test_results_partial_finishedsummary_dummy:
    pattern:  /test/finished-summary-dummy/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/Partial/FinishedSummary/Dummy:index }
    
app_task_results:
    pattern:  /{website}/{test_id}/{task_id}/results/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:results }  
    requirements:
        website: ".+"
        test_id: "\d+"
        task_id: "\d+" 
        
app_test_url_limit_notification:
    pattern:  /{website}/{test_id}/url-limit-notification/
    defaults: { _controller: SimplyTestableWebClientBundle:TestNotification:urlLimit }  
    requirements:
        website: ".+"
        test_id: "\d+"
      
app_task_results_redirector:
    pattern:  /{website}/{test_id}/{task_id}/
    defaults: { _controller: SimplyTestableWebClientBundle:Redirect:task }  
    requirements:
        website: ".+"
        test_id: "\d+"
        task_id: "\d+"         

app_progress:
    pattern:  /{website}/{test_id}/progress/
    defaults: { _controller: SimplyTestableWebClientBundle:TestProgress:index }  
    requirements:
        website: ".+" 
        
app_results:
    pattern:  /{website}/{test_id}/results/
    defaults: { _controller: SimplyTestableWebClientBundle:TestResults:index }  
    requirements:
       website: ".+"
       
app_test_lock:
    pattern:  /{website}/{test_id}/lock/
    defaults: { _controller: SimplyTestableWebClientBundle:Test:lock }  
    requirements:
       website: ".+"       
       
app_test_unlock:
    pattern:  /{website}/{test_id}/unlock/
    defaults: { _controller: SimplyTestableWebClientBundle:Test:unlock }  
    requirements:
       website: ".+"         
       
app_test_retest:
    pattern:  /{website}/{test_id}/re-test/
    defaults: { _controller: SimplyTestableWebClientBundle:Test:retest }  
    requirements:
       website: ".+"        

view_test_results_failednourlsdetected_index_index:
    pattern:  /{website}/{test_id}/results/failed/no-urls-detected/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/FailedNoUrlsDetected/Index:index }
    requirements:
       website: ".+"       

view_test_results_rejected_index_index:
    pattern:  /{website}/{test_id}/results/rejected/
    defaults: { _controller: SimplyTestableWebClientBundle:View/Test/Results/Rejected/Index:index }
    requirements:
       website: ".+"         
       
app_results_preparing:
    pattern:  /{website}/{test_id}/results/preparing/
    defaults: { _controller: SimplyTestableWebClientBundle:App:prepareResults }  
    requirements:
       website: ".+"       
       
app_results_preparing_stats:
    pattern:  /{website}/{test_id}/results/preparing/stats/
    defaults: { _controller: SimplyTestableWebClientBundle:App:prepareResultsStats, _format: json }  
    requirements:
       website: ".+"        
       
task_results_retrieve:
    pattern:  /{website}/{test_id}/results/retrieve/
    defaults: { _controller: SimplyTestableWebClientBundle:TaskResults:retrieve }  
    requirements:
       website: ".+"  
       
task_results_retrieve_status:
    pattern:  /{website}/{test_id}/results/retrieve/status/
    defaults: { _controller: SimplyTestableWebClientBundle:TaskResults:status }  
    requirements:
       website: ".+"         
        
app_tasks:
    pattern:  /{website}/{test_id}/tasks/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:collection, _format: json }  
    requirements:
        website: ".+"   
        
app_task_ids:
    pattern:  /{website}/{test_id}/tasks/ids/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:idCollection, _format: json }  
    requirements:
        website: ".+"
        
app_unretrieved_task_ids:
    pattern:  /{website}/{test_id}/tasks/ids/unretrieved/{limit}/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:unretrievedIdCollection, _format: json }  
    requirements:
        website: ".+"  

test_start:
    pattern:  /test/start/
    defaults: { _controller: SimplyTestableWebClientBundle:TestStart:startNew }             
    
test_cancel:
    pattern:  /test/{website}/{test_id}/cancel/
    defaults: { _controller: SimplyTestableWebClientBundle:Test:cancel }  
    requirements:
        website: ".+"
        
test_cancel_crawl:
    pattern:  /test/{website}/{test_id}/cancel-crawl/
    defaults: { _controller: SimplyTestableWebClientBundle:Test:cancelCrawl }  
    requirements:
        website: ".+"               
        
app_test_redirector:
    pattern:  /{website}/{test_id}/
    defaults: { _controller: SimplyTestableWebClientBundle:Redirect:test }  
    requirements:
        website: ".+"

app_website:
    pattern:  /{website}/
    defaults: { _controller: SimplyTestableWebClientBundle:Redirect:test }  
    requirements:
        website: ".+"         
        
outdated_browser:
    pattern:  /outdated-browser/
    defaults: { _controller: SimplyTestableWebClientBundle:App:outdatedBrowser }
