sign_in:
    pattern:  /signin/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signIn }  
    
sign_in_submit:
    pattern:  /signin/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signInSubmit }     
    
reset_password:
    pattern:  /reset-password/
    defaults: { _controller: SimplyTestableWebClientBundle:User:resetPassword }       
    
reset_password_submit:
    pattern:  /reset-password/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:User:resetPasswordSubmit }     
    
reset_password_confirm:
    pattern:  /reset-password/{email}/{token}/
    defaults: { _controller: SimplyTestableWebClientBundle:User:resetPasswordConfirm }     
    
sign_up:
    pattern:  /signup/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signUp }      
    
sign_up_submit:
    pattern:  /signup/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signUpSubmit }   
    
sign_up_confirm:
    pattern:  /signup/confirm/{email}/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signUpConfirm }       
    
sign_up_confirm_submit:
    pattern:  /signup/confirm/{email}/submit/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signUpConfirmSubmit }     
    
sign_up_confirm_resend:
    pattern:  /signup/confirm/{email}/resend/
    defaults: { _controller: SimplyTestableWebClientBundle:User:signUpConfirmResend }

app:
    pattern:  /
    defaults: { _controller: SimplyTestableWebClientBundle:App:index }
    
app_task_results:
    pattern:  /{website}/{test_id}/{task_id}/results/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:results }  
    requirements:
        website: ".+"
        test_id: "\d+"
        task_id: "\d+" 
        
app_task_results_redirector:
    pattern:  /{website}/{test_id}/{task_id}/
    defaults: { _controller: SimplyTestableWebClientBundle:Redirect:task }  
    requirements:
        website: ".+"
        test_id: "\d+"
        task_id: "\d+"         

app_progress:
    pattern:  /{website}/{test_id}/progress/
    defaults: { _controller: SimplyTestableWebClientBundle:App:progress }  
    requirements:
        website: ".+" 
        
app_results:
    pattern:  /{website}/{test_id}/results/
    defaults: { _controller: SimplyTestableWebClientBundle:App:results }  
    requirements:
       website: ".+"            
        
app_tasks:
    pattern:  /{website}/{test_id}/tasks/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:collection, _format: json }  
    requirements:
        website: ".+"   
        
app_task_ids:
    pattern:  /{website}/{test_id}/tasks/ids/
    defaults: { _controller: SimplyTestableWebClientBundle:Task:idCollection, _format: json }  
    requirements:
        website: ".+"

test_start:
    pattern:  /test/start/
    defaults: { _controller: SimplyTestableWebClientBundle:Test:start }
    
test_cancel:
    pattern:  /test/{website}/{test_id}/cancel/
    defaults: { _controller: SimplyTestableWebClientBundle:Test:cancel }  
    requirements:
        website: ".+"
        
app_test_redirector:
    pattern:  /{website}/{test_id}/
    defaults: { _controller: SimplyTestableWebClientBundle:Redirect:test }  
    requirements:
        website: ".+"   

app_website:
    pattern:  /{website}/
    defaults: { _controller: SimplyTestableWebClientBundle:Redirect:test }  
    requirements:
        website: ".+"         
        
outdated_browser:
    pattern:  /outdated-browser/
    defaults: { _controller: SimplyTestableWebClientBundle:App:outdatedBrowser }               
