services:
  simplytestable.services.httpClient:
    class:  webignition\Http\Client\Client
    
  simplytestable.services.webresourceservice:
    class:   SimplyTestable\WebClientBundle\Services\WebResourceService
    arguments:
        httpClient: "@simplytestable.services.httpClient"
        contentTypeWebResourceMap: %content_type_web_resource_map%    

  simplytestable.services.testservice:
    class:   SimplyTestable\WebClientBundle\Services\TestService  
    arguments:
        entityManager: "@doctrine.orm.entity_manager"  
        parameters: %core_application%
        webResourceService: "@simplytestable.services.webresourceservice"            
        taskOutputService: "@simplytestable.services.taskoutputservice"
        logger: "@logger"
        taskService: "@simplytestable.services.taskservice" 

  simplytestable.services.taskservice:
    class:   SimplyTestable\WebClientBundle\Services\TaskService  
    arguments:
        entityManager: "@doctrine.orm.entity_manager"  
        parameters: %core_application%
        webResourceService: "@simplytestable.services.webresourceservice"            
        taskOutputService: "@simplytestable.services.taskoutputservice"    

  simplytestable.services.taskoutputservice:
    class:   SimplyTestable\WebClientBundle\Services\TaskOutputService  
    arguments:
        entityManager: "@doctrine.orm.entity_manager"      
        parameters: %core_application%
        webResourceService: "@simplytestable.services.webresourceservice"
        taskOutputResultParserService: "@simplytestable.services.taskoutputresultparserfactoryservice" 

  simplytestable.services.taskoutputresultparserfactoryservice:
    class:   SimplyTestable\WebClientBundle\Services\TaskOutput\ResultParser\Factory
    arguments:
      drivers: %task-output-result-parsers%
      
  simplytestable.services.cachevalidatorheadersservice:
    class:   SimplyTestable\WebClientBundle\Services\CacheValidatorHeadersService  
    arguments:
        entityManager: "@doctrine.orm.entity_manager"      
        
  simplytestable.services.resqueQueueService:
    class:   SimplyTestable\WebClientBundle\Services\ResqueQueueService
    arguments:
      queueManager: "@glit_resque.queue_manager"
      logger: "@logger"
      resquePrefix: "%glit_resque.prefix%"                   
        
  simplytestable.services.websiteblocklistservice:
    class:  SimplyTestable\WebClientBundle\Services\WebsiteBlockListService      
    
  simplytestable.services.userservice:
    class:  SimplyTestable\WebClientBundle\Services\UserService        