services:
  
  simplytestable.services.httpClientService:
    class:  SimplyTestable\WebClientBundle\Services\TestHttpClientService   
  
  simplytestable.services.webresourceservice:
    class:   SimplyTestable\WebClientBundle\Services\TestWebResourceService
    arguments:
        httpClientService: "@simplytestable.services.httpClientService"
        contentTypeWebResourceMap: %content_type_web_resource_map%          