imports:
    - { resource: config_dev.yml }
    - { resource: "@SimplyTestableWebClientBundle/Resources/config/parameters_test.yml" }    
    - { resource: "@SimplyTestableWebClientBundle/Resources/config/services_test.yml" }      

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
  dbal:
    connections:
      default:
        driver: pdo_sqlite
        path: /run/shm/web.client.simplytestable.com.db